# Generated by Django 2.2.3 on 2019-07-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarService',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Service ID for specific days and dates')),
                ('start_date', models.DateField(verbose_name='Start date of this service schedule')),
                ('end_date', models.DateField(verbose_name='Planned end date for this service schedule I think, possibly redundant.')),
                ('monday', models.BooleanField(verbose_name='Serviced on this day')),
                ('tuesday', models.BooleanField(verbose_name='Serviced on this day')),
                ('wednesday', models.BooleanField(verbose_name='Serviced on this day')),
                ('thursday', models.BooleanField(verbose_name='Serviced on this day')),
                ('friday', models.BooleanField(verbose_name='Serviced on this day')),
                ('saturday', models.BooleanField(verbose_name='Serviced on this day')),
                ('sunday', models.BooleanField(verbose_name='Serviced on this day')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Route ID')),
                ('agency_id', models.CharField(max_length=20, verbose_name='Agency associated with data')),
                ('route_short_name', models.CharField(max_length=20, verbose_name='Line ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Bus stop ID')),
                ('stop_name', models.CharField(max_length=200, verbose_name='Stop Name')),
                ('stop_lat', models.FloatField(verbose_name='Stop Latitude')),
                ('stop_lng', models.FloatField(verbose_name='Stop Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Unique trip ID that represents a route, time of day, direction and specific calendar schedule')),
                ('direction', models.BooleanField(verbose_name='Indicates direction for bidirectional route_ids')),
                ('trip_headsign', models.CharField(max_length=200, verbose_name='Headsign to be used when no headsign change mid trip')),
                ('shape_id', models.CharField(max_length=100, verbose_name='Should be a FK for Shapes but shape id is not unique')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Routes', verbose_name='Route ID from Routes')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.CalendarService', verbose_name='Identifies the service schedule for this trip eg what days of week operational')),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=100, verbose_name='Identifies a shape')),
                ('shape_point_lat', models.FloatField(verbose_name='Shape Point Latitude')),
                ('shape_point_lng', models.FloatField(verbose_name='Shape Point Longitude')),
                ('shape_point_sequence', models.IntegerField(verbose_name='Point sequence along shape')),
                ('shape_dist_travelled', models.FloatField(verbose_name='Distance travelled so far to this point')),
            ],
            options={
                'unique_together': {('shape_id', 'shape_point_sequence')},
            },
        ),
        migrations.CreateModel(
            name='CalendarExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField(verbose_name='Date of exception')),
                ('exception_type', models.IntegerField(verbose_name='Type of exception, no info on types')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.CalendarService', verbose_name='Service ID from calendar table')),
            ],
            options={
                'unique_together': {('service_id', 'exception_date')},
            },
        ),
    ]
